# Generated by Django 5.0.6 on 2024-05-19 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='title')),
                ('description', models.CharField(max_length=300, verbose_name='description')),
                ('price', models.IntegerField(verbose_name='price')),
            ],
        ),
    ]
